[package]
name = "adt"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.3"
crypto = "0.5.1"
hex = "0.4.3"
rand = "0.8.5"
structopt = "0.3.26"